pipeline:
  name: DevTrack-CI
  identifier: DevTrackCI
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Checkout Code
        identifier: Checkout_Code
        description: Checkout the source code from GitHub
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Install Dependencies
                  identifier: Install_Dependencies
                  spec:
                    shell: Bash
                    command: npm install
              - step:
                  type: Run
                  name: Build Docker Image
                  identifier: Build_Docker_Image
                  spec:
                    shell: Bash
                    command: docker build -t devtrack-app .
              - step:
                  type: Run
                  name: Push Docker Image
                  identifier: Push_Docker_Image
                  spec:
                    shell: Bash
                    command: docker push devtrack-app
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1745403040158
        repoName: wrohanar/DevTrack
        branch: main
        build: <+input>
        sparseCheckout: []
